### PR TITLE
Adapt code for the latest (0.132.2) version of three js

### PR DESCRIPTION
**Pull request by NZhuravlev**
* Replace functions with classes
* Remove Geometry class usage
* Remove `getInverse` Matrix4 method usage

### CODE REVIEW

**Comment by wouterverweirder** [comment]
Confirming this works, would be nice to see this merged :-)

**Comment by doeg** [comment]
I've also confirmed that this fix works with three.js v.0.133.0. :)

**Comment by jiyinyiyong** [comment]
ping @spite

**Comment by robksawyer** [comment]
@spite where you at? Let's get it!

**Comment by Zaniyar** [comment]
how can I test this branch with npm in the meanwhile?

with this hash commit its same error:
"three.meshline": "https://github.com/spite/THREE.MeshLine.git#168f9b28a9cf1f123df874d2d253872cadfa209c",

**Comment by jrmahechad** [comment]
interested in this update

**Comment by Grepsy** [comment]
> how can I test this branch with npm in the meanwhile?
> 
> with this hash commit its same error: "three.meshline": "https://github.com/spite/THREE.MeshLine.git#168f9b28a9cf1f123df874d2d253872cadfa209c",

That's the current branch, you need the branch with the changes, like this:

`"three.meshline": "https://github.com/NZhuravlev/THREE.MeshLine.git#358d2f801de9b80f0708fbf4f2868a9ac7aa381c`

**Comment by spite** [comment]
I've merged the PR and published to npm. Can someone confirm it's working?

**Comment by tiye** [comment]
a least it is working(`THREE.Line` at left, `MeshLine` at right):

image

Meanwhile there's a warning in Vite since the code not using ES Modules(I guess):

```
WARNING: Multiple instances of Three.js being imported.
```

**Pull request merged**
