### PR TITLE
Correct line widths in any circumstances

### PR DESCRIPTION
**Pull request by axion014**
subset of #101.

### CODE REVIEW

**Comment by spite** [comment]
Hi! Thanks for the PR. I tested it and the graph.html example doesn't work as expected. Is there anything I'm missing?

**Comment by axion014** [comment]
The Graph demo were coded for current bugged MeshLine.
I didn't see why sizeAttenuation should be disabled here as line width is meant to be constant regardless of camera zooming, so I turned it to `false`(this syntax should definitely reversed).

**Comment by trusktr** [comment]
Can you explain what this does? Can you explain before/after?

**Comment by axion014** [comment]
Shader math is complicated and I mostly forgot what this does, but it basically fixes #26, making `lineWidth` behavior consistent between both type of cameras.

**Pull request merged**
