### PR TITLE
Fast advance() function for dynamic lines with demo

### PR DESCRIPTION
**Pull request by Jared-Sprague**
Hey @spite!  We started using this library to add dynamic trails to moving objects, and quickly learned that calling setGeometry() everytime the line changes, is very in efficient and slow as it completely rebuilds the line.  And 4 of the arrays that it build are static based on the length of the line and never change.  @mwcz and I created the `advance()` function advances the line by one position by modifying the buffer attribute typed arrays directly for Next, Current, and Previous positions.  This is so much faster than calling setGeometry() for 1 new position.   See the included demo that adds trails to the flocking birds demo.

### CODE REVIEW

**Comment by spite** [comment]
Nice work! 

I've reviewed the PR and i have a few changes and fixes for both the advance() and the boids demo. Do you mind if i merge our PR and then change it on the master branch?

**Comment by mwcz** [comment]
Sounds good to me!  @Jared-Sprague?  By the way, thank you @spite for making this!

**Comment by Jared-Sprague** [comment]
Sounds good thanks!

**Comment by spite** [comment]
Ok. That should be it. Merged and updated.

The most relevant changes should be:
For the lib: 
- Switched to memcpy to move all data inside arrays at once: https://github.com/spite/THREE.MeshLine/commit/eabdc73d3320ee827dd3090a81b2bacf29c942d8
For the demo:
- Added resolution update for line thickness https://github.com/spite/THREE.MeshLine/commit/0332eb370dfeeeb42002f6b3902179442546dff5 : you need to update the meshmaterial resolution uniform so it can adapt the line thickness accordingly. otherwise it look fat o skinny depending on how the user resizes the canvas
- Removed redundant appendChilda https://github.com/spite/THREE.MeshLine/commit/3e5237b65605d85075629355f6f8397c9765d240 : you were adding the renderer.domElement to the body, making container empty and blocking the events for OrbitControls.
- Added initial onWindowResize https://github.com/spite/THREE.MeshLine/commit/a0e3704c315cbdb28a5d788d6fdccf216aac7399 : so it can set all the appropriate sizes. it looked pixelated otherwise.

I think that's all, I hope I haven't broken anything.

Again, thanks for the work!

**Comment by Jared-Sprague** [comment]
@spite Ah i love the changes!  Especially the memcopy so clever!  

One question,  will you uplaod the trails demo and link to it from the readme?

**Comment by spite** [comment]
Yes, of course, with full credits! I can host it on my domain, or link to your online version.

**Comment by Jared-Sprague** [comment]
I think it makes the most sense to put it in the same location as the other demos.  I actually haven't uploaded it anywhere.  Thanks!

**Comment by Jared-Sprague** [comment]
@spite of course I'm happy to host the tail demo if you want!

**Comment by spite** [comment]
Sorry, I've been AFK until now. I've hosted it with the other demos, no worries. All done!

**Comment by Jared-Sprague** [comment]
@spite thanks you rock! and thanks for the mention!

**Pull request merged**
