### PR TITLE
Add raycast support - This closes #8

### LINKED ISSUE #8: Add raycast support
Make something similar to THREE.Line, accounting for the size attenuation flag, variable width, etc. features.

### PR DESCRIPTION
**Pull request by kappys1**
I add  the raycast function from THREE.js Library.
working with v91 THREE.js
solution mentionated in issue #8 Thanks @inDigiNeous and @spite

### CODE REVIEW

**Comment by kappys1** [comment]
Last Push (merge) for remove conflicts about the last update

**Comment by gvdlangenberg** [comment]
@spitea any idea if this will be merged some day?

**Comment by zachzeyuwang** [comment]
@spite Hey would this be merged someday?

**Comment by spite** [comment]
Merged, thank you!

**Comment by gvdlangenberg** [comment]
Any README update on how to use raycasting? My raycasting setup is still ignoring the Mesh added to the scene.

**Comment by mgss** [comment]
@spite Can you tell me how to use it? Use directly `raycaster.intersectObjects` Unable to capture

**Comment by sjlynch** [comment]
@spite @gvdlangenberg  @mgss Any of you figure out how to get raycasting working? I have it working for other threejs objects but not THREE.MeshLines. Using three v106dev

I tried playing with raycaster.linePrecision but no dice.

**Comment by gvdlangenberg** [comment]
No, I figured I could use a `CylinderGeometry` as well in my case.

**Comment by sjlynch** [comment]
@gvdlangenberg yeah i'm thinking of just using cubes or cylinders for lines but that's not as flexible as this library :/

**Comment by zachzeyuwang** [comment]
If you read the source code in line 83: https://github.com/spite/THREE.MeshLine/blob/master/src/THREE.MeshLine.js#L83, the correct way to call this function is `your_meshline.raycast(three_raycaster, returned_intersects)`.

**Comment by yuanzhaokang** [comment]
It will be better if there is an example about raycast. Thx.

**Comment by djy2017** [comment]
> @sjlynch If you read the source code in line 83: https://github.com/spite/THREE.MeshLine/blob/master/src/THREE.MeshLine.js#L83, the correct way to call this function is `your_meshline.raycast(three_raycaster, returned_intersects)`.

I have tried , but it did not work.
`function Test() {
      scene.traverse((o) => {
        if (o && o.type != 'Scene') {
          let arr = []
          o.raycast(raycaster, arr)
          if(arr.length > 0) {
            o.material.color = new THREE.Color('red')
          } else {
            o.material.color = new THREE.Color('green')
          }
        }
      })

      // console.log(arr)
    }`

**Comment by Jtfinlay** [comment]
> > @sjlynch If you read the source code in line 83: https://github.com/spite/THREE.MeshLine/blob/master/src/THREE.MeshLine.js#L83, the correct way to call this function is `your_meshline.raycast(three_raycaster, returned_intersects)`.
> 
> I have tried , but it did not work.
> 
> ```
> function Test() {
>       scene.traverse((o) => {
>         if (o && o.type != 'Scene') {
>           let arr = []
>           o.raycast(raycaster, arr)
>           if(arr.length > 0) {
>             o.material.color = new THREE.Color('red')
>           } else {
>             o.material.color = new THREE.Color('green')
>           }
>         }
>       })
>     }
> ```

Hey dij2017, I've been working through the same issue as you. The problem is that the PR adds support directly on the MeshLine object, while traversing the scene only acts on the  Mesh object. You could either hold the created MeshLine objects, or recreate them from the mesh data during traversal.

I did the latter and it worked for me,

```
function Test() {
      scene.traverse((o) => {
        if (o && o.type != 'Scene') {
          let arr = []
          o.raycast(raycaster, arr)
          if (o.material && o.material.isMeshLineMaterial) {
              const line = new MeshLine()
              // Converting to Geometry shouldn't be needed, but I hit an issue..
              line.setGeometry(
                  new Geometry().fromBufferGeometry(o.geometry)
              )
              line.raycast(raycaster, arr);
          }
          if(arr.length > 0) {
            o.material.color = new THREE.Color('red')
          } else {
            o.material.color = new THREE.Color('green')
          }
        }
      })
    }
```

**Pull request merged**
